export declare type getFileByKeysReturn = {
    path: string | undefined;
    dirpath: string | undefined;
    dirpaths: string[] | undefined;
    path_main: string | undefined;
    object: Record<string, any> | undefined;
    object_: Record<string, any> | undefined;
    object_main: mainFileType | undefined;
    object_main_: mainFileType | undefined;
    keyfound: boolean;
    filenum: number | undefined;
    keys: string | string[];
    leftkeys: string[];
    keynamesmatched: boolean;
};
export declare type mainFileEntry = Record<string, number>;
export declare type mainFileType = {
    keys: mainFileEntry[];
    filenum: number;
    filekeynum: number;
    num: number;
    keynames: string[];
    hasChanges?: string[];
    keysMoved?: boolean;
};
export declare type fileEntryType = Record<string, any>;
export declare type fileType = Record<string, any | fileEntryType>;
export declare type deleteKeySyncrettype = boolean | undefined;
export declare const maxJSONSize: 4194304;
export declare const defaultKeysFileSize: 200000;
export declare const defaultMoveToKeysFileChunkSize: 1000;
